# Generated by Django 4.2.7 on 2023-11-03 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='url_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя ссылки'),
        ),
    ]
