# Generated by Django 4.2.7 on 2023-11-03 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0002_menu_url_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='url_name',
        ),
    ]
