# Generated by Django 4.2.7 on 2023-11-03 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0003_remove_menu_url_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='position',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Позиция'),
        ),
    ]
